/* Klar A1 curriculum. Each lesson is intentionally compact: one communicative goal, a core phrase, and a small usable vocabulary set. */
const COURSE = [
  {
    unit: "A1.1",
    title: "First contact",
    lessons: [
      {
        id: 1,
        title: "Hello and goodbye",
        goal: "Greet someone naturally.",
        grammar:
          "Use Hallo in most informal situations. Guten Tag is more formal.",
        phrase: "Hallo! Wie geht es dir?",
        translation: "Hello! How are you?",
        vocab: [
          ["Hallo", "hello", ""],
          ["Tschüss", "bye", ""],
          ["danke", "thank you", ""],
          ["bitte", "please / you’re welcome", ""],
        ],
        quiz: [
          "How do you say “thank you”?",
          "danke",
          ["bitte", "Hallo", "Tschüss"],
        ],
      },
      {
        id: 2,
        title: "Introducing yourself",
        goal: "Say who you are.",
        grammar:
          "Ich bin means “I am”. German does not need a separate word for a/an here.",
        phrase: "Ich bin neu hier.",
        translation: "I am new here.",
        vocab: [
          ["ich", "I", ""],
          ["bin", "am", ""],
          ["heißen", "to be called", ""],
          ["neu", "new", ""],
        ],
        quiz: ["Complete: Ich ___ Anna.", "bin", ["bist", "heiße", "sein"]],
      },
      {
        id: 3,
        title: "Where are you from?",
        goal: "Talk about origin and language.",
        grammar: "kommen aus means “to come from”. The country follows aus.",
        phrase: "Ich komme aus Deutschland.",
        translation: "I come from Germany.",
        vocab: [
          ["kommen", "to come", ""],
          ["aus", "from", ""],
          ["sprechen", "to speak", ""],
          ["die Sprache", "language", "die"],
        ],
        quiz: [
          "Which phrase means “I come from…”?",
          "Ich komme aus",
          ["Ich bin aus", "Ich gehe aus", "Ich wohne aus"],
        ],
      },
      {
        id: 4,
        title: "The alphabet and spelling",
        goal: "Spell names and email addresses.",
        grammar: "Use wie schreibt man…? to ask how something is spelled.",
        phrase: "Wie schreibt man das?",
        translation: "How do you spell that?",
        vocab: [
          ["buchstabieren", "to spell", ""],
          ["der Buchstabe", "letter", "der"],
          ["das @", "at sign", "das"],
          ["die E-Mail", "email", "die"],
        ],
        quiz: [
          "What does Buchstabe mean?",
          "letter",
          ["number", "sentence", "name"],
        ],
      },
      {
        id: 5,
        title: "Numbers and phone numbers",
        goal: "Understand numbers 0–100.",
        grammar:
          "German two-digit numbers reverse the order: einundzwanzig = one-and-twenty.",
        phrase: "Meine Nummer ist null eins sieben…",
        translation: "My number is zero one seven…",
        vocab: [
          ["null", "zero", ""],
          ["zwanzig", "twenty", ""],
          ["hundert", "one hundred", ""],
          ["die Nummer", "number", "die"],
        ],
        quiz: ["What is zwanzig?", "twenty", ["twelve", "two", "one hundred"]],
      },
      {
        id: 6,
        title: "You and I",
        goal: "Ask simple personal questions.",
        grammar:
          "du is informal “you”; Sie is formal “you” and is always capitalised.",
        phrase: "Wo wohnst du?",
        translation: "Where do you live?",
        vocab: [
          ["du", "you (informal)", ""],
          ["Sie", "you (formal)", ""],
          ["wohnen", "to live", ""],
          ["wo", "where", ""],
        ],
        quiz: ["Which form is formal “you”?", "Sie", ["du", "ihr", "wir"]],
      },
    ],
  },
  {
    unit: "A1.2",
    title: "People and things",
    lessons: [
      {
        id: 7,
        title: "Nouns and gender",
        goal: "Meet der, die, and das.",
        grammar:
          "Every noun has a grammatical gender. Learn each noun together with its article.",
        phrase: "Das ist ein Buch.",
        translation: "That is a book.",
        vocab: [
          ["der Mann", "man", "der"],
          ["die Frau", "woman", "die"],
          ["das Buch", "book", "das"],
          ["das Kind", "child", "das"],
        ],
        quiz: ["Which article belongs to Buch?", "das", ["der", "die", "ein"]],
      },
      {
        id: 8,
        title: "My family",
        goal: "Describe close family.",
        grammar: "mein changes like ein: mein Vater, meine Mutter.",
        phrase: "Das ist meine Schwester.",
        translation: "This is my sister.",
        vocab: [
          ["die Familie", "family", "die"],
          ["der Vater", "father", "der"],
          ["die Mutter", "mother", "die"],
          ["der Bruder", "brother", "der"],
        ],
        quiz: [
          "What does Schwester mean?",
          "sister",
          ["mother", "brother", "daughter"],
        ],
      },
      {
        id: 9,
        title: "Jobs and study",
        goal: "Say what you do.",
        grammar: "sein is irregular: ich bin, du bist, er/sie ist.",
        phrase: "Ich arbeite als Lehrer.",
        translation: "I work as a teacher.",
        vocab: [
          ["arbeiten", "to work", ""],
          ["studieren", "to study", ""],
          ["der Beruf", "job / profession", "der"],
          ["der Student", "student", "der"],
        ],
        quiz: [
          "Complete: Ich ___ als Arzt.",
          "arbeite",
          ["arbeitest", "arbeiten", "arbeit"],
        ],
      },
      {
        id: 10,
        title: "Possession",
        goal: "Say what belongs to you.",
        grammar: "haben is “to have”: ich habe, du hast, er/sie hat.",
        phrase: "Ich habe einen Hund.",
        translation: "I have a dog.",
        vocab: [
          ["haben", "to have", ""],
          ["der Hund", "dog", "der"],
          ["die Katze", "cat", "die"],
          ["das Auto", "car", "das"],
        ],
        quiz: [
          "What does Ich habe mean?",
          "I have",
          ["I am", "I go", "I want"],
        ],
      },
      {
        id: 11,
        title: "Questions",
        goal: "Ask yes/no and information questions.",
        grammar: "For yes/no questions, the verb comes first: Hast du Zeit?",
        phrase: "Hast du heute Zeit?",
        translation: "Do you have time today?",
        vocab: [
          ["wer", "who", ""],
          ["was", "what", ""],
          ["wann", "when", ""],
          ["warum", "why", ""],
        ],
        quiz: ["Which word asks “when”?", "wann", ["warum", "wer", "was"]],
      },
      {
        id: 12,
        title: "Negation",
        goal: "Say no and not.",
        grammar:
          "kein negates nouns; nicht negates verbs, adjectives, or the rest of an idea.",
        phrase: "Ich habe keine Zeit.",
        translation: "I have no time.",
        vocab: [
          ["nicht", "not", ""],
          ["kein", "no / not a", ""],
          ["immer", "always", ""],
          ["heute", "today", ""],
        ],
        quiz: ["Choose the noun negator.", "kein", ["nicht", "nie", "auch"]],
      },
    ],
  },
  {
    unit: "A1.3",
    title: "Everyday life",
    lessons: [
      {
        id: 13,
        title: "A day in your life",
        goal: "Talk about routines.",
        grammar:
          "In a normal statement, the conjugated verb is in position two.",
        phrase: "Ich stehe um sieben Uhr auf.",
        translation: "I get up at seven o’clock.",
        vocab: [
          ["aufstehen", "to get up", ""],
          ["schlafen", "to sleep", ""],
          ["lernen", "to learn", ""],
          ["früh", "early", ""],
        ],
        quiz: [
          "Where is the verb in a normal German statement?",
          "position two",
          ["at the end", "first always", "anywhere"],
        ],
      },
      {
        id: 14,
        title: "Days and time",
        goal: "Make plans in time.",
        grammar:
          "Am is used with days: am Montag. Um is used with clock time: um acht Uhr.",
        phrase: "Am Montag arbeite ich.",
        translation: "On Monday I work.",
        vocab: [
          ["Montag", "Monday", ""],
          ["morgen", "tomorrow", ""],
          ["die Uhr", "clock / o’clock", "die"],
          ["spät", "late", ""],
        ],
        quiz: [
          "Choose the word for tomorrow.",
          "morgen",
          ["gestern", "heute", "Montag"],
        ],
      },
      {
        id: 15,
        title: "Food and drink",
        goal: "Order basic food and drinks.",
        grammar: "Ich möchte is a polite, useful way to say “I would like”.",
        phrase: "Ich möchte einen Kaffee, bitte.",
        translation: "I would like a coffee, please.",
        vocab: [
          ["das Wasser", "water", "das"],
          ["der Kaffee", "coffee", "der"],
          ["das Brot", "bread", "das"],
          ["möchten", "would like", ""],
        ],
        quiz: [
          "How do you politely say “I would like”?",
          "Ich möchte",
          ["Ich muss", "Ich kann", "Ich habe"],
        ],
      },
      {
        id: 16,
        title: "At a café",
        goal: "Order and pay.",
        grammar:
          "Bitte can mean please, here you are, or you’re welcome—context decides.",
        phrase: "Die Rechnung, bitte.",
        translation: "The bill, please.",
        vocab: [
          ["die Rechnung", "bill", "die"],
          ["zahlen", "to pay", ""],
          ["lecker", "tasty", ""],
          ["noch", "another / still", ""],
        ],
        quiz: ["What is die Rechnung?", "bill", ["menu", "table", "kitchen"]],
      },
      {
        id: 17,
        title: "Shopping",
        goal: "Ask for things in a shop.",
        grammar:
          "Was kostet…? asks the price. It literally means “What does … cost?”",
        phrase: "Was kostet das?",
        translation: "How much does that cost?",
        vocab: [
          ["kosten", "to cost", ""],
          ["kaufen", "to buy", ""],
          ["teuer", "expensive", ""],
          ["billig", "cheap", ""],
        ],
        quiz: [
          "What does teuer mean?",
          "expensive",
          ["cheap", "open", "small"],
        ],
      },
      {
        id: 18,
        title: "Likes and free time",
        goal: "Talk about interests.",
        grammar: "gern follows a verb and adds the meaning “gladly / like to”.",
        phrase: "Ich lese gern Bücher.",
        translation: "I like reading books.",
        vocab: [
          ["gern", "gladly / like to", ""],
          ["lesen", "to read", ""],
          ["hören", "to listen", ""],
          ["spielen", "to play", ""],
        ],
        quiz: [
          "What adds “like to” after a verb?",
          "gern",
          ["sehr", "nicht", "kein"],
        ],
      },
    ],
  },
  {
    unit: "A1.4",
    title: "Around town",
    lessons: [
      {
        id: 19,
        title: "Your home",
        goal: "Describe a room and home.",
        grammar: "Es gibt means “there is / there are”.",
        phrase: "In meiner Wohnung gibt es zwei Zimmer.",
        translation: "There are two rooms in my apartment.",
        vocab: [
          ["die Wohnung", "apartment", "die"],
          ["das Zimmer", "room", "das"],
          ["die Küche", "kitchen", "die"],
          ["das Bad", "bathroom", "das"],
        ],
        quiz: ["What does Zimmer mean?", "room", ["window", "door", "kitchen"]],
      },
      {
        id: 20,
        title: "The city",
        goal: "Find places in town.",
        grammar: "Wo ist…? is the core question for locating a place.",
        phrase: "Wo ist der Bahnhof?",
        translation: "Where is the train station?",
        vocab: [
          ["der Bahnhof", "train station", "der"],
          ["der Supermarkt", "supermarket", "der"],
          ["die Apotheke", "pharmacy", "die"],
          ["die Straße", "street", "die"],
        ],
        quiz: [
          "Which place sells medicine?",
          "die Apotheke",
          ["der Bahnhof", "der Park", "die Schule"],
        ],
      },
      {
        id: 21,
        title: "Directions",
        goal: "Understand simple directions.",
        grammar:
          "Geradeaus means straight ahead. Links and rechts do not change.",
        phrase: "Gehen Sie geradeaus und dann links.",
        translation: "Go straight ahead and then left.",
        vocab: [
          ["links", "left", ""],
          ["rechts", "right", ""],
          ["geradeaus", "straight ahead", ""],
          ["gehen", "to go", ""],
        ],
        quiz: [
          "What does geradeaus mean?",
          "straight ahead",
          ["right", "behind", "near"],
        ],
      },
      {
        id: 22,
        title: "Transport",
        goal: "Buy tickets and travel.",
        grammar: "mit means “with / by”: mit dem Bus, mit dem Zug.",
        phrase: "Ich fahre mit dem Bus.",
        translation: "I go by bus.",
        vocab: [
          ["der Bus", "bus", "der"],
          ["der Zug", "train", "der"],
          ["fahren", "to travel / drive", ""],
          ["das Ticket", "ticket", "das"],
        ],
        quiz: ["What does Zug mean?", "train", ["bus", "ticket", "station"]],
      },
      {
        id: 23,
        title: "The weather",
        goal: "Talk about today’s weather.",
        grammar: "Es ist… is used for weather: Es ist kalt.",
        phrase: "Heute ist es sonnig.",
        translation: "Today it is sunny.",
        vocab: [
          ["sonnig", "sunny", ""],
          ["kalt", "cold", ""],
          ["warm", "warm", ""],
          ["der Regen", "rain", "der"],
        ],
        quiz: ["What does kalt mean?", "cold", ["warm", "sunny", "rain"]],
      },
      {
        id: 24,
        title: "Clothes and colours",
        goal: "Describe what you wear.",
        grammar:
          "Adjectives often come before nouns: ein rotes Kleid. Learn common chunks first.",
        phrase: "Ich trage heute eine blaue Jacke.",
        translation: "I am wearing a blue jacket today.",
        vocab: [
          ["tragen", "to wear", ""],
          ["rot", "red", ""],
          ["blau", "blue", ""],
          ["die Jacke", "jacket", "die"],
        ],
        quiz: ["What does blau mean?", "blue", ["red", "black", "green"]],
      },
    ],
  },
  {
    unit: "A1.5",
    title: "Plans and conversations",
    lessons: [
      {
        id: 25,
        title: "Can and must",
        goal: "Talk about ability and obligation.",
        grammar:
          "Modal verbs send the main verb to the end: Ich kann Deutsch sprechen.",
        phrase: "Ich kann ein bisschen Deutsch sprechen.",
        translation: "I can speak a little German.",
        vocab: [
          ["können", "can / to be able to", ""],
          ["müssen", "must / have to", ""],
          ["wollen", "to want", ""],
          ["vielleicht", "maybe", ""],
        ],
        quiz: [
          "Where does the main verb go with können?",
          "at the end",
          ["position two", "before können", "it disappears"],
        ],
      },
      {
        id: 26,
        title: "Making plans",
        goal: "Invite someone and respond.",
        grammar:
          "Wollen wir…? is a friendly way to propose something: “Shall we…?”",
        phrase: "Wollen wir ins Kino gehen?",
        translation: "Shall we go to the cinema?",
        vocab: [
          ["treffen", "to meet", ""],
          ["das Kino", "cinema", "das"],
          ["zusammen", "together", ""],
          ["später", "later", ""],
        ],
        quiz: [
          "What does zusammen mean?",
          "together",
          ["tomorrow", "later", "alone"],
        ],
      },
      {
        id: 27,
        title: "Simple past: haben and sein",
        goal: "Talk about something that happened.",
        grammar:
          "In spoken German, the perfect tense is common: Ich habe gearbeitet.",
        phrase: "Ich habe gestern viel gelernt.",
        translation: "I studied a lot yesterday.",
        vocab: [
          ["gestern", "yesterday", ""],
          ["gemacht", "done / made", ""],
          ["gesehen", "seen", ""],
          ["gewesen", "been", ""],
        ],
        quiz: [
          "Which word means yesterday?",
          "gestern",
          ["morgen", "heute", "später"],
        ],
      },
      {
        id: 28,
        title: "Health and help",
        goal: "Explain a simple problem.",
        grammar:
          "Ich habe Schmerzen means “I have pain.” Use mir ist… for a feeling: Mir ist schlecht.",
        phrase: "Ich brauche einen Arzt.",
        translation: "I need a doctor.",
        vocab: [
          ["der Arzt", "doctor", "der"],
          ["krank", "ill", ""],
          ["helfen", "to help", ""],
          ["brauchen", "to need", ""],
        ],
        quiz: [
          "What does brauchen mean?",
          "to need",
          ["to help", "to hurt", "to go"],
        ],
      },
      {
        id: 29,
        title: "At a restaurant",
        goal: "Handle a full simple order.",
        grammar:
          "Nehmen is “to take”; Ich nehme… is another natural ordering phrase.",
        phrase: "Ich nehme die Suppe und ein Wasser.",
        translation: "I’ll have the soup and a water.",
        vocab: [
          ["die Speisekarte", "menu", "die"],
          ["die Suppe", "soup", "die"],
          ["vegetarisch", "vegetarian", ""],
          ["nehmen", "to take", ""],
        ],
        quiz: ["What is die Speisekarte?", "menu", ["bill", "soup", "table"]],
      },
      {
        id: 30,
        title: "Your first real conversation",
        goal: "Put A1 pieces together.",
        grammar:
          "You now have the building blocks: greeting, question, answer, and a simple follow-up.",
        phrase: "Freut mich, dich kennenzulernen.",
        translation: "Nice to meet you.",
        vocab: [
          ["freuen", "to be pleased", ""],
          ["kennenlernen", "to get to know", ""],
          ["wirklich", "really", ""],
          ["bis bald", "see you soon", ""],
        ],
        quiz: [
          "What does bis bald mean?",
          "see you soon",
          ["good morning", "thank you", "maybe later"],
        ],
      },
    ],
  },
];

const QUICK_PHRASES = [
  "Guten Morgen!",
  "Wie geht es dir?",
  "Ich lerne Deutsch.",
  "Entschuldigung, bitte langsam.",
  "Wo ist der Bahnhof?",
];
